# Generated by Django 3.1.4 on 2020-12-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Person_Name')),
                ('image', models.ImageField(upload_to='Images')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
