# Generated by Django 3.1.4 on 2020-12-03 07:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 7, 26, 43, 352963, tzinfo=utc)),
        ),
    ]
