# Generated by Django 3.1.4 on 2020-12-03 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognizer', '0002_auto_20201203_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Full_Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 8, 23, 4, 698723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='User_Name'),
        ),
    ]
