# Generated by Django 3.1.4 on 2020-12-03 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognizer', '0003_auto_20201203_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 8, 34, 5, 815529, tzinfo=utc)),
        ),
    ]
