# Generated by Django 3.1.4 on 2020-12-03 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognizer', '0004_auto_20201203_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 8, 36, 1, 701770, tzinfo=utc)),
        ),
    ]
