# Generated by Django 3.1.4 on 2020-12-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognizer', '0005_auto_20201203_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='timeStamp',
            field=models.DateTimeField(),
        ),
    ]
