# Generated by Django 3.1.4 on 2020-12-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognizer', '0006_auto_20201203_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Full_Name')),
                ('image', models.ImageField(upload_to='TempImages/')),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
    ]
